In [1]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import numpy as np

from sklearn.decomposition import PCA

# Scrape data 

In [ ]:
urls = ['https://en.wikipedia.org/wiki/Official_Women%27s_Squash_World_Ranking',
    'https://en.wikipedia.org/wiki/Official_Men%27s_Squash_World_Ranking']

In [ ]:
def is_not_numeric(s):
    try:
        float(s)
    except ValueError:
        return True
    else:
        return False


def table_to_pandas(table):
    """
    go to the urls to see what the tables look like. pointers
    * want to ignore first column (hence use `[1:]` in couple of places) 
      as that first column is just the ranks 1 to 10
    * use is_not_numeric to ignore the ranking points
    * top row of table has years
    
    returns pd.dataframe
        index is from 1 to 10
        column names are the years
        entries are player names
    """
    rows = table.find_all("tr")
    headers = [col.text.replace("\n", "") for col in rows[0].find_all("th")[1:]]

    data = [
        [
            col.text.replace("\n", "")
            for col in row.find_all("td")[1:]
            if is_not_numeric(col.text.replace("\n", ""))
        ]
        for row in rows[1:]
    ]

    return pd.DataFrame(data, columns=headers, index=range(1, 11))


def url_to_pandas(url):
    """
    given url, produce dataframe
    """
    html = requests.get(url).text
    start = html.find('id="Year_end_world_top_10_players')
    end = html.find('id="Year-end_number_1')
    tables = BeautifulSoup(html[start:end], "html.parser").find_all("table")
    
    # tables[1:] because first table does not fit the pattern of the other tables
    # go to the urls to see
    df = pd.concat([table_to_pandas(t) for t in tables[1:]], axis=1)
    
    # df.stack() creates new frame with multiindex consistenting of old
    # index and old columns. so df_stack multiindexx would be [rank, year] and have
    # single feature column of player names
    df_stack = df.stack().reset_index()
    df_stack.columns = ["rank", "year", "player"]

    return df_stack

In [ ]:
df_m = url_to_pandas(urls[1])
df_f = url_to_pandas(urls[0])

In [ ]:
df_m.to_csv('male_raw.csv')
df_f.to_csv('female_raw.csv')

# Process data

In [ ]:
def player_summaries(df):
    players = df.groupby("player").agg(
        {"rank": [np.mean, "count", np.min, np.max], "year": [np.min, np.max]}
    )

    players.columns = [
        "average_rank",
        "years_in_top10",
        "best_rank",
        "worst_rank",
        "earliest_year",
        "latest_year",
    ]
    players.sort_values(by=["average_rank"], inplace=True)

    return players

In [ ]:
players_f = player_summaries(pd.read_csv('female_raw.csv', index_col=0))
players_m = player_summaries(pd.read_csv('male_raw.csv', index_col=0))

In [ ]:
players_m.to_csv('male.csv')
players_f.to_csv('female.csv')

# visuals and clustering and dimensionality reduction

In [5]:
m = pd.read_csv('male.csv', index_col=0)

In [6]:
m

average_rank  years_in_top10  best_rank  worst_rank  \
player                                                                         
 Peter Nicol                 2.400000              10          1           8   
 Ali Farag                   3.250000               4          1           7   
 Jansher Khan                3.333333               3          1           8   
 Jonathon Power              3.666667               9          1           9   
 Mohamed El Shorbagy         3.700000              10          1          10   
 Ramy Ashour                 3.909091              11          1           7   
 Grégory Gaultier            4.000000              15          1          10   
 Ahmed Barada                4.250000               4          2           7   
 Rodney Eyles                4.333333               3          2           7   
 Nick Matthew                4.642857              14          1          10   
 David Palmer                4.727273              11          1           9   
 Amr Shabana                 4.727273              11          1           9   
 Paul Johnson                5.000000               3          4           7   
 Stewart Boswell             5.000000               2          4           6   
 Thierry Lincou              5.200000              10          1           9   
 James Willstrop             5.272727              11          1          10   
 Anthony Ricketts            5.500000               4          3           7   
 Karim Darwish               5.600000              10          1           9   
 Karim Abdel Gawad           5.666667               6          2           9   
 Martin Heath                5.666667               3          5           6   
 Del Harris                  6.000000               2          6           6   
 Dan Jenson                  6.000000               1          6           6   
 Marwan El Shorbagy          6.250000               4          5           9   
 John White                  6.571429               7          2          10   
 Paul Coll                   6.666667               3          5           8   
 Omar Mosaad                 6.666667               3          4           8   
 Tarek Momen                 6.800000               5          4          10   
 Lee Beachill                6.800000               5          1          10   
 Miguel Ángel Rodríguez      7.000000               3          5          10   
 Diego Elias                 7.000000               1          7           7   
 Stefan Casteleyn            7.000000               1          7           7   
 David Evans                 7.000000               2          4          10   
 Simon Parke                 7.000000               5          3          10   
 Craig Rowland               7.000000               1          7           7   
 Chris Walker                7.000000               2          4          10   
 Brett Martin                7.000000               2          5           9   
 Borja Golán                 7.000000               2          7           7   
 Peter Barker                7.142857               7          5           9   
 Anthony Hill                7.333333               3          5           9   
 Simon Rösner                7.500000               6          3          10   
 Ong Beng Hee                7.666667               3          7           8   
 Mark Chaloner               8.666667               3          8          10   
 Laurens Jan Anjema          9.000000               1          9           9   
 Alex Gough                  9.000000               2          9           9   
 Wael El Hindi               9.000000               3          8          10   
 Mathieu Castagnet           9.000000               2          9           9   
 Paul Price                  9.500000               2          9          10   
 Derek Ryan                 10.000000               1         10          10   
 Mohd Azlan Iskandar     

In [48]:
pca = PCA()
m_pca = pca.fit_transform(m)
m_pca = pd.DataFrame(m_pca, columns = ['pca1', 'pca2', 'pca3', 'pca4', 'pca5', 'pca6'],
                    index = m.index)
m_pca

pca1       pca2      pca3      pca4      pca5  \
player                                                                        
 Peter Nicol             -7.476936   8.752985  0.552572 -1.311669 -1.057366   
 Ali Farag               15.612668   0.402603  5.826557  0.238659 -0.270620   
 Jansher Khan           -13.292174   1.979958  3.979559  1.398703 -0.758381   
 Jonathon Power          -6.857177   7.364381  0.123749  0.079605 -0.768221   
 Mohamed El Shorbagy     12.278616   6.681417  0.356974  0.441340 -1.104049   
 Ramy Ashour              7.390437   7.977350  0.633991 -2.073599  0.351077   
 Grégory Gaultier         7.351065  12.398622 -3.440164 -1.347248 -0.399891   
 Ahmed Barada           -11.087805   1.995160  2.951062 -0.041546 -0.029137   
 Rodney Eyles           -13.324423   1.167023  3.369889  0.336136 -0.019619   
 Nick Matthew             7.184409  10.885256 -2.923990 -0.745820 -0.410750   
 David Palmer            -0.219698   8.823964 -1.426757 -0.485114  0.312572   
 Amr Shabana              4.655313   8.046664 -0.854401 -0.397811 -0.036240   
 Paul Johnson           -10.524417  -0.281241  2.134301 -0.629486 -0.204369   
 Stewart Boswell         -7.174083  -1.612130  3.420671 -1.019723  0.203608   
 Thierry Lincou          -0.388079   7.358786 -0.824549  0.076209  0.199864   
 James Willstrop          7.592731   8.344540 -1.851988  0.274899  0.581980   
 Anthony Ricketts        -3.310622   0.786485  2.065574 -0.413749  0.802158   
 Karim Darwish            3.173139   7.271135 -1.023018  0.069565  0.807708   
 Karim Abdel Gawad       15.208142   0.972868  2.154828  1.114739 -0.280574   
 Martin Heath           -10.560047  -0.999763  1.693199 -1.770631  0.334842   
 Del Harris             -14.208230  -2.277877  1.344317 -1.890860  0.195574   
 Dan Jenson             -12.229607  -3.458238  2.093370 -1.539640  0.164990   
 Marwan El Shorbagy      15.675435  -2.414382  1.245850  0.187766 -0.526016   
 John White              -4.163410   4.504668 -1.402183  1.458625  0.896257   
 Paul Coll               16.219272  -3.612737  2.129453 -0.099704  0.124874   
 Omar Mosaad             10.694076  -1.929523  1.818078  0.277990  1.127471   
 Tarek Momen             14.491218  -0.583911  0.134380  1.168109  0.055573   
 Lee Beachill            -3.093341   2.156529  0.806047  2.969120  0.540128   
 Miguel Ángel Rodríguez  14.972104  -2.853701  0.509763  1.269004  0.171023   
 Diego Elias             17.318044  -6.851460  2.617715 -1.171559  0.101658   
 Stefan Casteleyn       -10.789193  -4.345944  0.697151 -1.126110  0.036417   
 David Evans             -8.424558  -1.952325  0.548079  2.410757 -0.343549   
 Simon Parke            -11.540964   1.842651 -0.961771  1.911669  0.049912   
 Craig Rowland          -15.005278  -3.970117  0.409067 -1.119292  0.026630   
 Chris Walker           -14.046005  -1.451222  0.163966  2.419847 -0.356597   
 Brett Martin           -14.088396  -1.980917  0.060001  1.121545 -0.216486   
 Borja Golán              9.717974  -5.169995  1.484549 -1.513689  0.119193   
 Peter Barker             6.937897   1.124361 -1.644889 -0.650872  0.093719   
 Anthony Hill           -12.506478  -0.869324 -0.853808  0.747966  0.382032   
 Simon Rösner            14.592721   0.375877 -0.043112  1.632867  0.445062   
 Ong Beng Hee            -6.273856  -2.900450 -1.003211 -0.945843  0.080957   
 Mark Chaloner          -10.246214  -1.906463 -4.169864 -0.165063  0.944953   
 Laurens Jan Anjema       4.739893  -7.248838 -1.231033 -0.319502 -0.191372   
 Alex Gough              -9.886986  -4.940995 -2.844340 -0.650269 -0.190147   
 Wael El Hindi            2.230400  -4.483696 -2.529146  0.274087 -0.267055   
 Mathieu Castagnet       12.598803  -6.945407 -1.307889 -0.686629 -0.137954   
 Paul Price              -8.442903  -5.182638 -3.442453  0.204510 -0.322859   
 Derek Ryan             -12.089396  -6.507959 -3.875619  0.123570 -0.362353   
 Mohd Azlan Iskandar      6.180308  -8.136544 -2.627252  0.094028 -0.319946   
 

In [49]:
pca.transform(
    np.array(
        [[2.4, 10, 1, 8, 1996, 2005]]
    )
)

array([[-7.47693593,  8.75298503,  0.55257224, -1.3116692 , -1.0573659 ,
         0.52552363]])

In [37]:
pca.transform(np.array([[2, 8, 1, 5, 2000, 2010]]))

array([[-1.38538908,  7.25839028,  3.01209462, -3.21025431,  1.03348237,
         1.41643398]])

In [50]:
pca.inverse_transform(
    np.array(
        [[-7.47693593, 8.75298503, 0.55257224, -1.3116692, -1.0573659, 0.52552363]]
    )
)

array([[2.40000000e+00, 1.00000000e+01, 1.00000000e+00, 7.99999999e+00,
        1.99600000e+03, 2.00500000e+03]])

In [38]:
pca.inverse_transform(
    np.array(
        [[-1.38538908, 7.25839028, 3.01209462, -3.21025431, 1.03348237, 1.41643398]]
    )
)

array([[2.00000000e+00, 8.00000000e+00, 9.99999996e-01, 5.00000000e+00,
        2.00000000e+03, 2.01000000e+03]])

### Predictions of original data using subset of components

In [64]:
m_pca1 = m_pca.copy()
m_pca1[['pca2', 'pca3', 'pca4', 'pca5', 'pca6']] = 0
m_pca1

pca1  pca2  pca3  pca4  pca5  pca6
player                                                          
 Peter Nicol             -7.476936   0.0   0.0   0.0   0.0   0.0
 Ali Farag               15.612668   0.0   0.0   0.0   0.0   0.0
 Jansher Khan           -13.292174   0.0   0.0   0.0   0.0   0.0
 Jonathon Power          -6.857177   0.0   0.0   0.0   0.0   0.0
 Mohamed El Shorbagy     12.278616   0.0   0.0   0.0   0.0   0.0
 Ramy Ashour              7.390437   0.0   0.0   0.0   0.0   0.0
 Grégory Gaultier         7.351065   0.0   0.0   0.0   0.0   0.0
 Ahmed Barada           -11.087805   0.0   0.0   0.0   0.0   0.0
 Rodney Eyles           -13.324423   0.0   0.0   0.0   0.0   0.0
 Nick Matthew             7.184409   0.0   0.0   0.0   0.0   0.0
 David Palmer            -0.219698   0.0   0.0   0.0   0.0   0.0
 Amr Shabana              4.655313   0.0   0.0   0.0   0.0   0.0
 Paul Johnson           -10.524417   0.0   0.0   0.0   0.0   0.0
 Stewart Boswell         -7.174083   0.0   0.0   0.0   0.0   0.0
 Thierry Lincou          -0.388079   0.0   0.0   0.0   0.0   0.0
 James Willstrop          7.592731   0.0   0.0   0.0   0.0   0.0
 Anthony Ricketts        -3.310622   0.0   0.0   0.0   0.0   0.0
 Karim Darwish            3.173139   0.0   0.0   0.0   0.0   0.0
 Karim Abdel Gawad       15.208142   0.0   0.0   0.0   0.0   0.0
 Martin Heath           -10.560047   0.0   0.0   0.0   0.0   0.0
 Del Harris             -14.208230   0.0   0.0   0.0   0.0   0.0
 Dan Jenson             -12.229607   0.0   0.0   0.0   0.0   0.0
 Marwan El Shorbagy      15.675435   0.0   0.0   0.0   0.0   0.0
 John White              -4.163410   0.0   0.0   0.0   0.0   0.0
 Paul Coll               16.219272   0.0   0.0   0.0   0.0   0.0
 Omar Mosaad             10.694076   0.0   0.0   0.0   0.0   0.0
 Tarek Momen             14.491218   0.0   0.0   0.0   0.0   0.0
 Lee Beachill            -3.093341   0.0   0.0   0.0   0.0   0.0
 Miguel Ángel Rodríguez  14.972104   0.0   0.0   0.0   0.0   0.0
 Diego Elias             17.318044   0.0   0.0   0.0   0.0   0.0
 Stefan Casteleyn       -10.789193   0.0   0.0   0.0   0.0   0.0
 David Evans             -8.424558   0.0   0.0   0.0   0.0   0.0
 Simon Parke            -11.540964   0.0   0.0   0.0   0.0   0.0
 Craig Rowland          -15.005278   0.0   0.0   0.0   0.0   0.0
 Chris Walker           -14.046005   0.0   0.0   0.0   0.0   0.0
 Brett Martin           -14.088396   0.0   0.0   0.0   0.0   0.0
 Borja Golán              9.717974   0.0   0.0   0.0   0.0   0.0
 Peter Barker             6.937897   0.0   0.0   0.0   0.0   0.0
 Anthony Hill           -12.506478   0.0   0.0   0.0   0.0   0.0
 Simon Rösner            14.592721   0.0   0.0   0.0   0.0   0.0
 Ong Beng Hee            -6.273856   0.0   0.0   0.0   0.0   0.0
 Mark Chaloner          -10.246214   0.0   0.0   0.0   0.0   0.0
 Laurens Jan Anjema       4.739893   0.0   0.0   0.0   0.0   0.0
 Alex Gough              -9.886986   0.0   0.0   0.0   0.0   0.0
 Wael El Hindi            2.230400   0.0   0.0   0.0   0.0   0.0
 Mathieu Castagnet       12.598803   0.0   0.0   0.0   0.0   0.0
 Paul Price              -8.442903   0.0   0.0   0.0   0.0   0.0
 Derek Ryan             -12.089396   0.0   0.0   0.0   0.0   0.0
 Mohd Azlan Iskandar      6.180308   0.0   0.0   0.0   0.0   0.0
 Mohamed Abouelghar      16.017841   0.0   0.0   0.0   0.0   0.0
 Daryl Selby              8.417771   0.0   0.0   0.0   0.0   0.0

In [65]:
pd.concat([m, pd.DataFrame(pca.inverse_transform(m_pca1), index=m.index)], axis=1)

average_rank  years_in_top10  best_rank  worst_rank  \
player                                                                         
 Peter Nicol                 2.400000              10          1           8   
 Ali Farag                   3.250000               4          1           7   
 Jansher Khan                3.333333               3          1           8   
 Jonathon Power              3.666667               9          1           9   
 Mohamed El Shorbagy         3.700000              10          1          10   
 Ramy Ashour                 3.909091              11          1           7   
 Grégory Gaultier            4.000000              15          1          10   
 Ahmed Barada                4.250000               4          2           7   
 Rodney Eyles                4.333333               3          2           7   
 Nick Matthew                4.642857              14          1          10   
 David Palmer                4.727273              11          1           9   
 Amr Shabana                 4.727273              11          1           9   
 Paul Johnson                5.000000               3          4           7   
 Stewart Boswell             5.000000               2          4           6   
 Thierry Lincou              5.200000              10          1           9   
 James Willstrop             5.272727              11          1          10   
 Anthony Ricketts            5.500000               4          3           7   
 Karim Darwish               5.600000              10          1           9   
 Karim Abdel Gawad           5.666667               6          2           9   
 Martin Heath                5.666667               3          5           6   
 Del Harris                  6.000000               2          6           6   
 Dan Jenson                  6.000000               1          6           6   
 Marwan El Shorbagy          6.250000               4          5           9   
 John White                  6.571429               7          2          10   
 Paul Coll                   6.666667               3          5           8   
 Omar Mosaad                 6.666667               3          4           8   
 Tarek Momen                 6.800000               5          4          10   
 Lee Beachill                6.800000               5          1          10   
 Miguel Ángel Rodríguez      7.000000               3          5          10   
 Diego Elias                 7.000000               1          7           7   
 Stefan Casteleyn            7.000000               1          7           7   
 David Evans                 7.000000               2          4          10   
 Simon Parke                 7.000000               5          3          10   
 Craig Rowland               7.000000               1          7           7   
 Chris Walker                7.000000               2          4          10   
 Brett Martin                7.000000               2          5           9   
 Borja Golán                 7.000000               2          7           7   
 Peter Barker                7.142857               7          5           9   
 Anthony Hill                7.333333               3          5           9   
 Simon Rösner                7.500000               6          3          10   
 Ong Beng Hee                7.666667               3          7           8   
 Mark Chaloner               8.666667               3          8          10   
 Laurens Jan Anjema          9.000000               1          9           9   
 Alex Gough                  9.000000               2          9           9   
 Wael El Hindi               9.000000               3          8          10   
 Mathieu Castagnet           9.000000               2          9           9   
 Paul Price                  9.500000               2          9          10   
 Derek Ryan                 10.000000               1         10          10   
 Mohd Azlan Iskandar     

In [67]:
m_pca2 = m_pca.copy()
m_pca2[['pca3', 'pca4', 'pca5', 'pca6']] = 0
m_pca2

pca1       pca2  pca3  pca4  pca5  pca6
player                                                               
 Peter Nicol             -7.476936   8.752985   0.0   0.0   0.0   0.0
 Ali Farag               15.612668   0.402603   0.0   0.0   0.0   0.0
 Jansher Khan           -13.292174   1.979958   0.0   0.0   0.0   0.0
 Jonathon Power          -6.857177   7.364381   0.0   0.0   0.0   0.0
 Mohamed El Shorbagy     12.278616   6.681417   0.0   0.0   0.0   0.0
 Ramy Ashour              7.390437   7.977350   0.0   0.0   0.0   0.0
 Grégory Gaultier         7.351065  12.398622   0.0   0.0   0.0   0.0
 Ahmed Barada           -11.087805   1.995160   0.0   0.0   0.0   0.0
 Rodney Eyles           -13.324423   1.167023   0.0   0.0   0.0   0.0
 Nick Matthew             7.184409  10.885256   0.0   0.0   0.0   0.0
 David Palmer            -0.219698   8.823964   0.0   0.0   0.0   0.0
 Amr Shabana              4.655313   8.046664   0.0   0.0   0.0   0.0
 Paul Johnson           -10.524417  -0.281241   0.0   0.0   0.0   0.0
 Stewart Boswell         -7.174083  -1.612130   0.0   0.0   0.0   0.0
 Thierry Lincou          -0.388079   7.358786   0.0   0.0   0.0   0.0
 James Willstrop          7.592731   8.344540   0.0   0.0   0.0   0.0
 Anthony Ricketts        -3.310622   0.786485   0.0   0.0   0.0   0.0
 Karim Darwish            3.173139   7.271135   0.0   0.0   0.0   0.0
 Karim Abdel Gawad       15.208142   0.972868   0.0   0.0   0.0   0.0
 Martin Heath           -10.560047  -0.999763   0.0   0.0   0.0   0.0
 Del Harris             -14.208230  -2.277877   0.0   0.0   0.0   0.0
 Dan Jenson             -12.229607  -3.458238   0.0   0.0   0.0   0.0
 Marwan El Shorbagy      15.675435  -2.414382   0.0   0.0   0.0   0.0
 John White              -4.163410   4.504668   0.0   0.0   0.0   0.0
 Paul Coll               16.219272  -3.612737   0.0   0.0   0.0   0.0
 Omar Mosaad             10.694076  -1.929523   0.0   0.0   0.0   0.0
 Tarek Momen             14.491218  -0.583911   0.0   0.0   0.0   0.0
 Lee Beachill            -3.093341   2.156529   0.0   0.0   0.0   0.0
 Miguel Ángel Rodríguez  14.972104  -2.853701   0.0   0.0   0.0   0.0
 Diego Elias             17.318044  -6.851460   0.0   0.0   0.0   0.0
 Stefan Casteleyn       -10.789193  -4.345944   0.0   0.0   0.0   0.0
 David Evans             -8.424558  -1.952325   0.0   0.0   0.0   0.0
 Simon Parke            -11.540964   1.842651   0.0   0.0   0.0   0.0
 Craig Rowland          -15.005278  -3.970117   0.0   0.0   0.0   0.0
 Chris Walker           -14.046005  -1.451222   0.0   0.0   0.0   0.0
 Brett Martin           -14.088396  -1.980917   0.0   0.0   0.0   0.0
 Borja Golán              9.717974  -5.169995   0.0   0.0   0.0   0.0
 Peter Barker             6.937897   1.124361   0.0   0.0   0.0   0.0
 Anthony Hill           -12.506478  -0.869324   0.0   0.0   0.0   0.0
 Simon Rösner            14.592721   0.375877   0.0   0.0   0.0   0.0
 Ong Beng Hee            -6.273856  -2.900450   0.0   0.0   0.0   0.0
 Mark Chaloner          -10.246214  -1.906463   0.0   0.0   0.0   0.0
 Laurens Jan Anjema       4.739893  -7.248838   0.0   0.0   0.0   0.0
 Alex Gough              -9.886986  -4.940995   0.0   0.0   0.0   0.0
 Wael El Hindi            2.230400  -4.483696   0.0   0.0   0.0   0.0
 Mathieu Castagnet       12.598803  -6.945407   0.0   0.0   0.0   0.0
 Paul Price              -8.442903  -5.182638   0.0   0.0   0.0   0.0
 Derek Ryan             -12.089396  -6.507959   0.0   0.0   0.0   0.0
 Mohd Azlan Iskandar      6.180308  -8.136544   0.0   0.0   0.0   0.0
 Mohamed Abouelghar      16.017841  -9.013475   0.0   0.0   0.0   0.0
 Daryl Selby              8.417771  -7.332010   0.0   0.0   0.0   0.0

In [68]:
pd.concat([m, pd.DataFrame(pca.inverse_transform(m_pca2), index=m.index)], axis=1)

average_rank  years_in_top10  best_rank  worst_rank  \
player                                                                         
 Peter Nicol                 2.400000              10          1           8   
 Ali Farag                   3.250000               4          1           7   
 Jansher Khan                3.333333               3          1           8   
 Jonathon Power              3.666667               9          1           9   
 Mohamed El Shorbagy         3.700000              10          1          10   
 Ramy Ashour                 3.909091              11          1           7   
 Grégory Gaultier            4.000000              15          1          10   
 Ahmed Barada                4.250000               4          2           7   
 Rodney Eyles                4.333333               3          2           7   
 Nick Matthew                4.642857              14          1          10   
 David Palmer                4.727273              11          1           9   
 Amr Shabana                 4.727273              11          1           9   
 Paul Johnson                5.000000               3          4           7   
 Stewart Boswell             5.000000               2          4           6   
 Thierry Lincou              5.200000              10          1           9   
 James Willstrop             5.272727              11          1          10   
 Anthony Ricketts            5.500000               4          3           7   
 Karim Darwish               5.600000              10          1           9   
 Karim Abdel Gawad           5.666667               6          2           9   
 Martin Heath                5.666667               3          5           6   
 Del Harris                  6.000000               2          6           6   
 Dan Jenson                  6.000000               1          6           6   
 Marwan El Shorbagy          6.250000               4          5           9   
 John White                  6.571429               7          2          10   
 Paul Coll                   6.666667               3          5           8   
 Omar Mosaad                 6.666667               3          4           8   
 Tarek Momen                 6.800000               5          4          10   
 Lee Beachill                6.800000               5          1          10   
 Miguel Ángel Rodríguez      7.000000               3          5          10   
 Diego Elias                 7.000000               1          7           7   
 Stefan Casteleyn            7.000000               1          7           7   
 David Evans                 7.000000               2          4          10   
 Simon Parke                 7.000000               5          3          10   
 Craig Rowland               7.000000               1          7           7   
 Chris Walker                7.000000               2          4          10   
 Brett Martin                7.000000               2          5           9   
 Borja Golán                 7.000000               2          7           7   
 Peter Barker                7.142857               7          5           9   
 Anthony Hill                7.333333               3          5           9   
 Simon Rösner                7.500000               6          3          10   
 Ong Beng Hee                7.666667               3          7           8   
 Mark Chaloner               8.666667               3          8          10   
 Laurens Jan Anjema          9.000000               1          9           9   
 Alex Gough                  9.000000               2          9           9   
 Wael El Hindi               9.000000               3          8          10   
 Mathieu Castagnet           9.000000               2          9           9   
 Paul Price                  9.500000               2          9          10   
 Derek Ryan                 10.000000               1         10          10   
 Mohd Azlan Iskandar     

In [69]:
pca.explained_variance_

array([118.81586177,  29.39876913,   4.86314221,   1.31442008,
         0.22146742,   0.18436197])

In [70]:
pca.explained_variance_ratio_

array([0.76755413, 0.18991696, 0.03141605, 0.00849119, 0.00143069,
       0.00119098])